// Catálogo de productos recomendados en las guías.
// - Sin precios ni imágenes de tienda: los programas de afiliados no permiten copiarlos.
// - asin: si lo rellenas, el enlace va a la ficha exacta (/dp/ASIN). Si no, a una búsqueda en Amazon.
// - pccUrl: enlace de afiliado de PcComponentes (solo se muestra con pccomponentesActive: true).
// - reviewed: fecha de la última comprobación de ficha, variante y disponibilidad.
export default {
  "kingston-nv3-1tb": {
    name: "Kingston NV3 1 TB",
    category: "SSD NVMe",
    glyph: "SSD",
    why: "Opción equilibrada para dar el salto a NVMe en portátiles y sobremesa con ranura M.2 compatible.",
    specs: ["M.2 2280", "NVMe PCIe 4.0", "1 TB"],
    amazonSearch: "Kingston NV3 1TB NVMe",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "crucial-p3-plus-1tb": {
    name: "Crucial P3 Plus 1 TB",
    category: "SSD NVMe",
    glyph: "SSD",
    why: "Alternativa de gama media para quien quiere 1 TB sin pagar por la máxima velocidad.",
    specs: ["M.2 2280", "NVMe PCIe 4.0", "1 TB"],
    amazonSearch: "Crucial P3 Plus 1TB",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "wd-black-sn770-1tb": {
    name: "WD Black SN770 1 TB",
    category: "SSD NVMe",
    glyph: "SSD",
    why: "Un paso por encima en rendimiento para equipo principal o juegos, si la ranura lo admite.",
    specs: ["M.2 2280", "NVMe PCIe 4.0", "1 TB"],
    amazonSearch: "WD Black SN770 1TB",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "corsair-vengeance-ddr5-32-6000": {
    name: "Corsair Vengeance DDR5 32 GB (2×16) 6000 MHz",
    category: "RAM sobremesa",
    glyph: "RAM",
    why: "Kit de dos módulos para placas DDR5. Comprueba antes la lista de memorias compatibles de tu placa.",
    specs: ["DDR5", "DIMM", "2×16 GB"],
    amazonSearch: "Corsair Vengeance DDR5 32GB 6000",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "kingston-fury-beast-ddr4-32-3200": {
    name: "Kingston FURY Beast DDR4 32 GB 3200 MHz",
    category: "RAM sobremesa",
    glyph: "RAM",
    why: "Para ampliar equipos DDR4 que aún tienen recorrido, sin cambiar de plataforma.",
    specs: ["DDR4", "DIMM", "32 GB"],
    amazonSearch: "Kingston FURY Beast DDR4 32GB 3200",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "crucial-pro-ddr5-32-5600": {
    name: "Crucial Pro DDR5 32 GB 5600 MHz",
    category: "RAM sobremesa",
    glyph: "RAM",
    why: "Memoria DDR5 sobria, sin iluminación, pensada para equipos de trabajo.",
    specs: ["DDR5", "DIMM", "32 GB"],
    amazonSearch: "Crucial Pro DDR5 32GB 5600",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "lg-ultragear-27-qhd": {
    name: "LG UltraGear 27\" QHD IPS",
    category: "Monitor",
    glyph: "27\"",
    why: "27 pulgadas QHD con panel IPS: buen equilibrio entre espacio de trabajo, nitidez y juego ocasional.",
    specs: ["27\"", "2560×1440", "IPS"],
    amazonSearch: "LG UltraGear 27 QHD IPS",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "msi-g274qpf": {
    name: "MSI G274QPF 27\" QHD",
    category: "Monitor",
    glyph: "27\"",
    why: "Otra opción de 27\" QHD para quien combina trabajo y juego.",
    specs: ["27\"", "2560×1440"],
    amazonSearch: "MSI G274QPF",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "samsung-odyssey-g5-27": {
    name: "Samsung Odyssey G5 27\" QHD",
    category: "Monitor",
    glyph: "27\"",
    why: "27\" QHD de la gama Odyssey; revisa la variante exacta, porque hay modelos curvos y planos.",
    specs: ["27\"", "2560×1440"],
    amazonSearch: "Samsung Odyssey G5 27 QHD",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "logitech-mx-keys-s": {
    name: "Logitech MX Keys S",
    category: "Teclado",
    glyph: "KEY",
    why: "Teclado cómodo para muchas horas de escritura, con conexión a varios equipos.",
    specs: ["Inalámbrico", "Multidispositivo"],
    amazonSearch: "Logitech MX Keys S",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "logitech-mx-master-3s": {
    name: "Logitech MX Master 3S",
    category: "Ratón",
    glyph: "MX",
    why: "Ratón ergonómico de referencia para trabajo de oficina, programación y diseño ligero.",
    specs: ["Inalámbrico", "Ergonómico"],
    amazonSearch: "Logitech MX Master 3S",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
  "hyperx-cloud-iii": {
    name: "HyperX Cloud III",
    category: "Auriculares",
    glyph: "AUD",
    why: "Auriculares con micrófono para reuniones y juego, cómodos en sesiones largas.",
    specs: ["Con micrófono"],
    amazonSearch: "HyperX Cloud III",
    asin: "",
    pccUrl: "",
    reviewed: "[FECHA DE REVISIÓN]",
  },
};
