// Buscador por síntoma de /servicios/: qué reviso primero y qué servicio suele encajar.
export default [
  {
    id: "no-arranca",
    label: "No enciende o no arranca",
    checks: ["Alimentación, cargador y batería", "Memoria y disco", "Señales de la placa al pulsar el botón"],
    usually: "Muchas veces es una pieza concreta (cargador, memoria, disco) y no el equipo entero.",
    meanwhile: "No lo abras ni lo fuerces; si ha sufrido un golpe o líquido, desconéctalo.",
    service: "diagnostico-reparacion",
  },
  {
    id: "lento",
    label: "Va muy lento",
    checks: ["Tipo y estado del disco", "Memoria disponible", "Programas que arrancan solos", "Temperaturas"],
    usually: "Un cambio a SSD y algo más de memoria suelen devolverle la agilidad sin comprar otro.",
    meanwhile: "Apunta qué programas usas a diario: ayuda a decidir cuánta memoria hace falta.",
    service: "ssd-ram",
  },
  {
    id: "calor-ruido",
    label: "Se calienta o hace ruido",
    checks: ["Ventiladores y polvo acumulado", "Pasta térmica", "Uso del procesador en reposo"],
    usually: "Una limpieza interna con pasta térmica nueva lo resuelve en la mayoría de los casos.",
    meanwhile: "Úsalo sobre una superficie dura, nunca sobre cojines o mantas.",
    service: "diagnostico-reparacion",
  },
  {
    id: "virus-errores",
    label: "Virus, errores o ventanas raras",
    checks: ["Programas instalados sin querer", "Extensiones del navegador", "Estado del sistema"],
    usually: "Si el sistema está muy tocado, lo más limpio es reinstalarlo conservando tus datos.",
    meanwhile: "No introduzcas contraseñas ni datos bancarios en ese equipo hasta revisarlo.",
    service: "formateo",
  },
  {
    id: "datos",
    label: "He perdido archivos o el disco falla",
    checks: ["Salud del disco", "Si los archivos son recuperables", "Copia inmediata de lo importante"],
    usually: "Cuanto antes se actúe, más posibilidades hay de recuperar los archivos.",
    meanwhile: "Deja de usar ese disco: cada uso puede sobrescribir lo que quieres recuperar.",
    service: "discos-datos",
  },
  {
    id: "comprar",
    label: "Quiero comprar o montar uno",
    checks: ["Para qué lo vas a usar", "Presupuesto real", "Compatibilidad entre piezas"],
    usually: "Una buena elección evita pagar por potencia que no vas a aprovechar.",
    meanwhile: "Las guías de compra te ayudan a llegar con las ideas más claras.",
    service: "montaje-compra",
  },
  {
    id: "negocio",
    label: "Mi negocio necesita orden",
    checks: ["Equipos y red del local", "Copias de seguridad", "Correo y cuentas"],
    usually: "Un mantenimiento periódico y unas copias automáticas evitan la mayoría de los sustos.",
    meanwhile: "Si no tienes copia de lo importante, ese es el primer paso.",
    service: "negocios",
  },
  {
    id: "tarea",
    label: "Una tarea me roba horas",
    checks: ["Cómo se hace hoy, paso a paso", "Qué datos intervienen", "Dónde hace falta una persona"],
    usually: "Muchas tareas repetitivas se pueden automatizar con reglas sencillas o con ayuda de IA.",
    meanwhile: "Cronometra cuánto te lleva a la semana: así sabremos si compensa.",
    service: "automatizacion",
  },
];
